{
    'name': "Final Year Dissertaion Management",
    'summary': "Odoo module for managing final year dissertation at the Department of Mathematics and Computer Science at ENSET SKIKDA",
    'author': 'Department of Mathematics and Computer Science',
    'category': 'Education',
    'version': '16.0.0.1',
    'depends': ['base', 'event', 'portal', 'hr', 'contacts', 'web', 'website', 'web_responsive', 'mail'],
    'sequence': 1,
    'data': [
        'security/groups.xml',
        'data/teacher_categories.xml',
        'data/education_specializations.xml',
        'data/event.xml',
        'data/email.xml',
        'data/ir_sequence_data.xml',
        'views/education_specialization.xml',
        'views/student.xml',
        'views/sgroupe.xml',
        'views/topic.xml',
        'views/dissertation.xml',
        'views/topic_categories.xml',
        'views/defense.xml',
        'views/menu.xml',
        'views/website_menu.xml',
        'views/choose_diss.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'security/portal.xml',
        'security/topic_security.xml',
        'views/website_topic_submit_templateA.xml',
        'views/template_defense_creat.xml',
        'views/portal_template.xml',
        'views/departement.xml',
        'views/Topic_details.xml',
        'views/list_topic.xml',
        'views/list_topic_public.xml',
        'views/portal_dissertation_portal.xml',
        'views/eventview.xml',
        'views/login.xml',
        'reports/dissertation_re.xml',
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
}  
