from . import student
from . import dissertation
from . import topic
from . import defense
from . import session
from . import announce
from . import teacher
from . import sgroupe
from . import specialization
from . import education_level
from . import dissertation_avancement
from . import choose_list
from . import _departement
from . import grade
from . import topic_categories
